### PR TITLE
Don't initialize classes when registering matchers

### LINKED ISSUE #637: Unexpected crash in interaction with Google Analytics
Tests unexpectedly crash when the Google Analytics CocoaPod is also included alongside Kiwi in the test target.

The error triggers a EXC_BAD_ACCESS in registerMatcherClassesWithNamespacePrefix at this line https://github.com/kiwi-bdd/Kiwi/blob/master/Classes/Core/KWMatcherFactory.m#L76. At the time of error candidateClass is GAITrackedModel.

An example project demonstrating this issue is available here: https://github.com/indiegogo/GoogleAnalyticsKiwiCrash

A discussion of the error is also found here: https://groups.google.com/forum/#!topic/kiwi-bdd/ZfLol8_Oz8k

### PR DESCRIPTION
**Pull request by yas375**
It's possible that a library may have some assertions in theirs `+initialize` methods to help developers to find a potential problem in theirs setup. I.e. Facebook SDK makes sure you have specified required url scheme before you [use FBSDKAppInviteDialog](https://github.com/facebook/facebook-ios-sdk/blob/61b636f61d67337d59741177289cdfe5ec0e5667/FBSDKShareKit/FBSDKShareKit/FBSDKAppInviteDialog.m#L35) or [FBSDKShareDialog](https://github.com/facebook/facebook-ios-sdk/blob/61b636f61d67337d59741177289cdfe5ec0e5667/FBSDKShareKit/FBSDKShareKit/FBSDKShareDialog.m#L60), or [FBSDKShareKit/FBSDKMessageDialog](https://github.com/facebook/facebook-ios-sdk/blob/61b636f61d67337d59741177289cdfe5ec0e5667/FBSDKShareKit/FBSDKShareKit/FBSDKMessageDialog.m#L39).

So we've just upgraded to the latest Facebook SDK and have started seeing exceptions when running tests. Those exceptions were exactly in those `+initialize` methods in FB sdk classes. But we don't use those features in our app so we don't need to set up all requirements it asserts for. It works fine when we run our apps because we never call those classes and theirs `+initialize` methods never called.

When we run tests `KWMatcherFactory#registerMatcherClassesWithNamespacePrefix:` is called and it loops through all available classes and check who conforms to `KWMatching` protocol. To check this, it uses `NSObject#conformsToProtocol:` which triggers `+initialize` call.

> + initialize
> Initializes the class before it receives its first message.
> **Discussion**
> The runtime sends initialize to each class in a program just before the class, or any class that inherits from it, is sent its first message from within the program.

This doesn't look right. Kiwi doesn't need to trigger `initialize` methods for every class it can see in runtime. The solution is simply to use `class_conformsToProtocol()` function for this.

I believe this closes #637, #638, https://groups.google.com/forum/m/#!topic/kiwi-bdd/ZfLol8_Oz8k

### CODE REVIEW

**Comment by glentregoning** [comment]
:+1: this PR, this is fixes the root cause of integration issues with Google Analytics / Facebook SDK (and others).

**Comment by IndieKevin** [comment]
+1 on the fix

**Comment by yas375** [comment]
Any feedback on this from maintainers please? Would be very nice to get it merged in. thanks in advance!

**Comment by glentregoning** [comment]
*bump*

It'd be great to get this fix onto master.

**Comment by ravelantunes** [comment]
Same issue here. Would be great to have it merged!

**Comment by ldrr** [comment]
Same issue here, could you please merge?

**Comment by gligorkot** [comment]
Same issue here, could you please merge this fix?

**Comment by orta** [comment]
OK, cool, looks good to me, let's do it.

**Pull request merged**
