### PR TITLE
Add shared examples.

### PR DESCRIPTION
**Pull request by modocache**
Shared examples allow developers to reuse a set of describe, context,
and it nodes to test one or more classes. See the functional tests in
`Tests/Shared Examples/KWSharedExampleFunctionalTest.m` for sample
usage.

Addresses issues #175, #138.

- `KWSharedExampleRegistry` is a singleton that maintains a mapping of
  shared example names to `KWSharedExample` instances.
- `KWSharedExample` is a data structure composed of a name and context
  block.
- `sharedExamplesFor` creates a `KWSharedExample` and registers it.
- `itBehavesLike` looks up the `KWSharedExample` with the given name and
  inserts its context block into the current example group.
- `SHARED_EXAMPLES_BEGIN`, `SHARED_EXAMPLES_END` macros are used to
  ensure `sharedExamplesFor` are evaluated prior to any examples.
- In order to allow assertion macros like `should` to be compiled outside
  of the implementation block of a `KWSpec`--like within `sharedExamplesFor`,
  for example--changed macro to reference global state by using
  `KWSpec` class method.
- Changed all pragma marks referencing internal/private methods to
  `Internal Methods`.
- Removed unused `KWEncodingForVoidMethod` function.

# Sample Usage

```objc
// CruiserSpecHelpers.m

SHARED_EXAMPLES_BEGIN(CruiserSpecHelpers)

sharedExamplesFor(@"a cruiser", ^(Class describedClass) {
    __block Cruiser *cruiser = nil;
    beforeEach(^{
        cruiser = [[describedClass alloc] initWithCallsign:@"Planet Express"];
    });

    it(@"has a callsign", ^{
        [[cruiser.callsign should] equal:@"Planet Express"];
    });
});

SHARED_EXAMPLES_END
```

```objc
// CruiserSpec.m

SPEC_BEGIN(CruiserSpec)

describe(@"Cruiser", ^{
    itBehavesLike(@"a cruiser", [Cruiser class]);
});

describe(@"Carrier", ^{
    itBehavesLike(@"a cruiser", [Carrier class]);
});

SPEC_END
```

# Additional Comments

Feedback very much appreciated! Especially with regards to the following:

- I'm not particularly thrilled with the use of macros--I'd prefer to use @sharplet's `CONFIG_START` and `CONFIG_END` macros, but they don't seem to be working for me.
- Test failures are highlighted in Xcode on the line of the `it` block in the `sharedExamplesFor` block, **not** on the line with `itBehavesLike`. I don't know how to make the `itBehavesLike` block highlighted. Callsites? :confused:

### CODE REVIEW

**Comment by ecaselles** [comment]
@modocache @supermarin I was wondering what happened to this PR. Any reason why it has not been merged yet, 2.3 was released about 8 months ago? i.e. Is it just a due to lack of time or are there any breaking issues?

**Comment by modocache** [comment]
@ecaselles Lack of time. Feel free to fork, rebase, and re-submit the PR. You could also improve it by fixing the `itBehavesLike` bug I mention above! :+1:

**Comment by ecaselles** [comment]
@modocache I have created PR #600 which basically rebases this PR on top of the current Kiwi version. As part of it, I have also upgraded the tests to run on ```XCTest``` instead of ```SenTestKit```. Feel free to review it and leave feedback.

**Comment by sharplet** [comment]
Closed via #600.

**Pull request closed without merging**
