### PR TITLE
Rename any() macros to kw_any()

### PR DESCRIPTION
**Pull request by SergeyKuryanov**
This address issue: #698

As any other solution was provided, simple macros renaming.

### CODE REVIEW

**Comment by orta** [comment]
This is a major semver bump /cc @sharplet

**Comment by SergeyKuryanov** [comment]
Tests pass locally, not sure why `beforeAllSpecs`, `afterAllSpecs` should be executed.

**Comment by ecaselles** [comment]
Agree @orta. 

@SergeyKuryanov Thanks for doing this! I was thinking... would it be possible to check if `any` is defined? In case it is, define` kw_any` instead. Otherwise, keep defining `any` to keep backwards compatibility.

**Comment by SergeyKuryanov** [comment]
@ecaselles  
Checking for `any` deined is not working for me, seems like `any` macros setting appear before `Project-Swift.h` definitions, so that check won't help.

Something like `#if __has_attribute(external_source_symbol)` is working, but I don't think this is reliable check.

**Comment by ecaselles** [comment]
Thanks @SergeyKuryanov, so... I guess we will have to introduce this as a breaking change, won't we?

**Comment by orta** [comment]
I don't hold much sentiment on major version bumps ( Danger is on 5 for example )- this sounds like something people need to keep up to date with Xcode's ever changing build tooling , so we shouldn't be precious.

Do it IMO

**Comment by SergeyKuryanov** [comment]
@ecaselles I don't like Idea of breaking change, but this only one way to make it work (at least I didn't found another). So I guess we should do it.

**Comment by ecaselles** [comment]
Fair enough! Thanks @orta and @SergeyKuryanov. We’ve got a decision 👌

**Comment by ecaselles** [comment]
> Tests pass locally, not sure why beforeAllSpecs, afterAllSpecs should be executed.

@SergeyKuryanov after investigating a bit, I believe the tests fail because of the check done in [test_suite_configuration.rb](https://github.com/kiwi-bdd/Kiwi/blob/9429e0a439ea2dfc8de9d4a2cd9ff449bcf456d8/test_suite_configuration.rb#L12), which expects Xcode's logs to contain mentions to `beforeAllSpec` and `afterAllSpec`. I believe its purpose is just to check these [two](https://github.com/kiwi-bdd/Kiwi/blob/9429e0a439ea2dfc8de9d4a2cd9ff449bcf456d8/Tests/Config.m#L7) [lines](https://github.com/kiwi-bdd/Kiwi/blob/9429e0a439ea2dfc8de9d4a2cd9ff449bcf456d8/Tests/Config.m#L13) run. Not sure why it is not being printed any more though or how would this PR break it. Maybe @sharplet could help us here, since he was the one introducing the check.

In the meantime, I am downloading Xcode 7.3 to see if I can reproduce it locally, but I am not sure why that would be a problem in this PR.

**Comment by ecaselles** [comment]
After having a chat with @sharplet, I think I have a better understanding of why this might be failing. I still need to check a couple things before I can resolve it. I will keep this thread updated, but I will continue working on #703, in order to keep this one clean.

**Comment by ecaselles** [comment]
Solved the issue with tests (#703). Now this requires a rebase on top of master.

**Comment by ecaselles** [comment]
Closed in favour of #704 (same changes, rebased on top of master so the build passes)

**Comment by ecaselles** [comment]
Closed in favour of #704 (same changes, rebased on top of master so the build passes).

**Pull request closed without merging**
